# Cloudflare Wrangler Configuration for Pages
name = "smokesim-website"

# Required for Cloudflare Pages
pages_build_output_dir = "dist"

# Environment variables for build
[vars]
NODE_ENV = "production"

# Compatibility settings (use latest date)
compatibility_date = "2024-10-02"