# Cloudflare Wrangler Configuration
name = "smokesim-website"

# Required for Cloudflare Pages
pages_build_output_dir = "dist"

# Build configuration (optional - usually handled by GitHub Actions)
[build]
command = "npm run build"
cwd = "."

# Environment variables for build
[vars]
NODE_ENV = "production"

# Compatibility settings (use latest date)
compatibility_date = "2024-10-02"