# Cloudflare Wrangler Configuration
name = "smokesim-website"

# Cloudflare Pages configuration
[env.production]
pages_build_output_dir = "dist"

# Build configuration (optional - usually handled by GitHub Actions)
[build]
command = "npm run build"
cwd = "."

# Environment variables for build
[env.production.vars]
NODE_ENV = "production"

# Compatibility settings (use latest date)
compatibility_date = "2024-10-02"
compatibility_flags = ["nodejs_compat"]

# Custom domain configuration (managed via Cloudflare Dashboard)
# Domain: smokesim.co.uk